// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arithmetic.proto

package com.googlecode.protobuf.minarpc.example;

public final class Arithmetic {
  private Arithmetic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class OpResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use OpResponse.newBuilder() to construct.
    private OpResponse() {
      initFields();
    }
    private OpResponse(boolean noInit) {}
    
    private static final OpResponse defaultInstance;
    public static OpResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public OpResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.minarpc.example.Arithmetic.internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.minarpc.example.Arithmetic.internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_fieldAccessorTable;
    }
    
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean hasResult;
    private int result_ = 0;
    public boolean hasResult() { return hasResult; }
    public int getResult() { return result_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasResult) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasResult()) {
        output.writeInt32(1, getResult());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getResult());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse result;
      
      // Construct using com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse();
        return builder;
      }
      
      protected com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDescriptor();
      }
      
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse getDefaultInstanceForType() {
        return com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse) {
          return mergeFrom((com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse other) {
        if (other == com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setResult(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 result = 1;
      public boolean hasResult() {
        return result.hasResult();
      }
      public int getResult() {
        return result.getResult();
      }
      public Builder setResult(int value) {
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder clearResult() {
        result.hasResult = false;
        result.result_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.googlecode.protobuf.minarpc.services.OpResponse)
    }
    
    static {
      defaultInstance = new OpResponse(true);
      com.googlecode.protobuf.minarpc.example.Arithmetic.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.googlecode.protobuf.minarpc.services.OpResponse)
  }
  
  public static final class OpRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use OpRequest.newBuilder() to construct.
    private OpRequest() {
      initFields();
    }
    private OpRequest(boolean noInit) {}
    
    private static final OpRequest defaultInstance;
    public static OpRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public OpRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.googlecode.protobuf.minarpc.example.Arithmetic.internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.googlecode.protobuf.minarpc.example.Arithmetic.internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_fieldAccessorTable;
    }
    
    // required string operator = 1;
    public static final int OPERATOR_FIELD_NUMBER = 1;
    private boolean hasOperator;
    private java.lang.String operator_ = "";
    public boolean hasOperator() { return hasOperator; }
    public java.lang.String getOperator() { return operator_; }
    
    // repeated int32 operands = 2;
    public static final int OPERANDS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> operands_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getOperandsList() {
      return operands_;
    }
    public int getOperandsCount() { return operands_.size(); }
    public int getOperands(int index) {
      return operands_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasOperator) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOperator()) {
        output.writeString(1, getOperator());
      }
      for (int element : getOperandsList()) {
        output.writeInt32(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOperator()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getOperator());
      }
      {
        int dataSize = 0;
        for (int element : getOperandsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getOperandsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest result;
      
      // Construct using com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest();
        return builder;
      }
      
      protected com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.getDescriptor();
      }
      
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest getDefaultInstanceForType() {
        return com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.operands_ != java.util.Collections.EMPTY_LIST) {
          result.operands_ =
            java.util.Collections.unmodifiableList(result.operands_);
        }
        com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest) {
          return mergeFrom((com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest other) {
        if (other == com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.getDefaultInstance()) return this;
        if (other.hasOperator()) {
          setOperator(other.getOperator());
        }
        if (!other.operands_.isEmpty()) {
          if (result.operands_.isEmpty()) {
            result.operands_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.operands_.addAll(other.operands_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setOperator(input.readString());
              break;
            }
            case 16: {
              addOperands(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addOperands(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required string operator = 1;
      public boolean hasOperator() {
        return result.hasOperator();
      }
      public java.lang.String getOperator() {
        return result.getOperator();
      }
      public Builder setOperator(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOperator = true;
        result.operator_ = value;
        return this;
      }
      public Builder clearOperator() {
        result.hasOperator = false;
        result.operator_ = getDefaultInstance().getOperator();
        return this;
      }
      
      // repeated int32 operands = 2;
      public java.util.List<java.lang.Integer> getOperandsList() {
        return java.util.Collections.unmodifiableList(result.operands_);
      }
      public int getOperandsCount() {
        return result.getOperandsCount();
      }
      public int getOperands(int index) {
        return result.getOperands(index);
      }
      public Builder setOperands(int index, int value) {
        result.operands_.set(index, value);
        return this;
      }
      public Builder addOperands(int value) {
        if (result.operands_.isEmpty()) {
          result.operands_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.operands_.add(value);
        return this;
      }
      public Builder addAllOperands(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.operands_.isEmpty()) {
          result.operands_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.operands_);
        return this;
      }
      public Builder clearOperands() {
        result.operands_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.googlecode.protobuf.minarpc.services.OpRequest)
    }
    
    static {
      defaultInstance = new OpRequest(true);
      com.googlecode.protobuf.minarpc.example.Arithmetic.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.googlecode.protobuf.minarpc.services.OpRequest)
  }
  
  public static abstract class ArithmeticService
      implements com.google.protobuf.Service {
    protected ArithmeticService() {}
    
    public interface Interface {
      public abstract void performOperation(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ArithmeticService() {
        @Override
        public  void performOperation(
            com.google.protobuf.RpcController controller,
            com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest request,
            com.google.protobuf.RpcCallback<com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse> done) {
          impl.performOperation(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.performOperation(controller, (com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void performOperation(
        com.google.protobuf.RpcController controller,
        com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest request,
        com.google.protobuf.RpcCallback<com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.googlecode.protobuf.minarpc.example.Arithmetic.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.performOperation(controller, (com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest)request,
            com.google.protobuf.RpcUtil.<com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.googlecode.protobuf.minarpc.example.Arithmetic.ArithmeticService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void performOperation(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest request,
          com.google.protobuf.RpcCallback<com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.class,
            com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse performOperation(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse performOperation(
          com.google.protobuf.RpcController controller,
          com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020arithmetic.proto\022(com.googlecode.proto" +
      "buf.minarpc.services\"\034\n\nOpResponse\022\016\n\006re" +
      "sult\030\001 \002(\005\"/\n\tOpRequest\022\020\n\010operator\030\001 \002(" +
      "\t\022\020\n\010operands\030\002 \003(\0052\222\001\n\021ArithmeticServic" +
      "e\022}\n\020performOperation\0223.com.googlecode.p" +
      "rotobuf.minarpc.services.OpRequest\0324.com" +
      ".googlecode.protobuf.minarpc.services.Op" +
      "Response"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_googlecode_protobuf_minarpc_services_OpResponse_descriptor,
              new java.lang.String[] { "Result", },
              com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.class,
              com.googlecode.protobuf.minarpc.example.Arithmetic.OpResponse.Builder.class);
          internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_googlecode_protobuf_minarpc_services_OpRequest_descriptor,
              new java.lang.String[] { "Operator", "Operands", },
              com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.class,
              com.googlecode.protobuf.minarpc.example.Arithmetic.OpRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
