# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='arithmetic.proto',
  package='com.googlecode.protobuf.minarpc.services',
  serialized_pb='\n\x10\x61rithmetic.proto\x12(com.googlecode.protobuf.minarpc.services\"\x1c\n\nOpResponse\x12\x0e\n\x06result\x18\x01 \x02(\x05\"/\n\tOpRequest\x12\x10\n\x08operator\x18\x01 \x02(\t\x12\x10\n\x08operands\x18\x02 \x03(\x05\x32\x92\x01\n\x11\x41rithmeticService\x12}\n\x10performOperation\x12\x33.com.googlecode.protobuf.minarpc.services.OpRequest\x1a\x34.com.googlecode.protobuf.minarpc.services.OpResponse')




_OPRESPONSE = descriptor.Descriptor(
  name='OpResponse',
  full_name='com.googlecode.protobuf.minarpc.services.OpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='com.googlecode.protobuf.minarpc.services.OpResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=90,
)


_OPREQUEST = descriptor.Descriptor(
  name='OpRequest',
  full_name='com.googlecode.protobuf.minarpc.services.OpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='operator', full_name='com.googlecode.protobuf.minarpc.services.OpRequest.operator', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operands', full_name='com.googlecode.protobuf.minarpc.services.OpRequest.operands', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=139,
)



class OpResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OPRESPONSE
  
  # @@protoc_insertion_point(class_scope:com.googlecode.protobuf.minarpc.services.OpResponse)

class OpRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OPREQUEST
  
  # @@protoc_insertion_point(class_scope:com.googlecode.protobuf.minarpc.services.OpRequest)


_ARITHMETICSERVICE = descriptor.ServiceDescriptor(
  name='ArithmeticService',
  full_name='com.googlecode.protobuf.minarpc.services.ArithmeticService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=142,
  serialized_end=288,
  methods=[
  descriptor.MethodDescriptor(
    name='performOperation',
    full_name='com.googlecode.protobuf.minarpc.services.ArithmeticService.performOperation',
    index=0,
    containing_service=None,
    input_type=_OPREQUEST,
    output_type=_OPRESPONSE,
    options=None,
  ),
])

class ArithmeticService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ARITHMETICSERVICE
class ArithmeticService_Stub(ArithmeticService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ARITHMETICSERVICE

# @@protoc_insertion_point(module_scope)
